#!MC 1300
# Created by Tecplot 360 build 13.1.1.16309

$!FIELDLAYERS SHOWMESH = YES
$!FRAMECONTROL ACTIVATEBYNUMBER
  FRAME = 1
$!SETFRAMEBACKGROUNDCOLOR WHITE
$!SLICEATTRIBUTES 3  SHOWGROUP = YES
$!GLOBALCONTOUR 1  LEGEND{SHOW = YES}
$!GLOBALCONTOUR 1  LEGEND{AUTORESIZE = YES}
$!GLOBALCONTOUR 1  LEGEND{OVERLAYBARGRID = NO}
$!GLOBALCONTOUR 1  COLORMAPFILTER{COLORMAPDISTRIBUTION = CONTINUOUS}